#!/bin/bash

################################################################################
# Dotfiles Update & PR Script
#
# This script:
# 1. Syncs currently installed packages to Brewfile
# 2. Validates the Brewfile syntax
# 3. Commits changes to a new branch
# 4. Pushes to GitHub
# 5. Creates a pull request
#
# Usage: ./update-and-pr.sh [message]
################################################################################

set -e

# Configuration
TARGET_REPO="${DOTFILES_REPO:-github.com/mccainfamily/dotfiles}"
BRANCH_PREFIX="update"
DEFAULT_MESSAGE="Update Brewfile with latest packages"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Functions
log_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1"
}

# Check if we're in the dotfiles directory
if [[ ! -f "brew/Brewfile" ]]; then
    log_error "Must be run from dotfiles repository root"
    log_info "Run: cd ~/.dotfiles && ./scripts/update-and-pr.sh"
    exit 1
fi

# Check for gh CLI
if ! command -v gh &> /dev/null; then
    log_error "GitHub CLI (gh) is required but not installed"
    log_info "Install with: brew install gh"
    exit 1
fi

# Check if authenticated with GitHub
if ! gh auth status &> /dev/null; then
    log_error "Not authenticated with GitHub"
    log_info "Run: gh auth login"
    exit 1
fi

log_info "Starting dotfiles update process..."
echo

# Step 1: Sync Brewfile
log_info "Syncing Brewfile with installed packages..."
./scripts/brew-sync.sh
log_success "Brewfile synced"

# Step 2: Validate Brewfile
log_info "Validating Brewfile syntax..."
if brew bundle check --file=brew/Brewfile --verbose; then
    log_success "Brewfile validation passed"
else
    log_warning "Brewfile validation warnings (non-critical)"
fi

# Step 3: Check for changes
log_info "Checking for changes..."
if git diff --quiet brew/Brewfile; then
    log_warning "No changes detected in Brewfile"
    echo
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_info "Cancelled"
        exit 0
    fi
fi

# Step 4: Get commit message
COMMIT_MESSAGE="${1:-$DEFAULT_MESSAGE}"
log_info "Commit message: $COMMIT_MESSAGE"

# Step 5: Create branch
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BRANCH_NAME="${BRANCH_PREFIX}-${TIMESTAMP}"
log_info "Creating branch: $BRANCH_NAME"

# Get current branch to return to later
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Create and checkout new branch
git checkout -b "$BRANCH_NAME"
log_success "Branch created"

# Step 6: Stage and commit changes
log_info "Staging changes..."
git add brew/Brewfile

# Also stage any other modified tracked files
if [[ -n $(git diff --cached --name-only) ]]; then
    log_info "Files staged:"
    git diff --cached --name-only | sed 's/^/  - /'

    log_info "Committing changes..."
    git commit -m "$COMMIT_MESSAGE"
    log_success "Changes committed"
else
    log_error "No changes to commit"
    git checkout "$CURRENT_BRANCH"
    git branch -D "$BRANCH_NAME"
    exit 1
fi

# Step 7: Push to remote
log_info "Pushing to remote..."
git push -u origin "$BRANCH_NAME"
log_success "Pushed to origin/$BRANCH_NAME"

# Step 8: Create pull request
log_info "Creating pull request..."

# Extract repo owner and name from TARGET_REPO
REPO_PATH=$(echo "$TARGET_REPO" | sed 's/github.com\///')

PR_BODY="## Dotfiles Update

This PR updates the Brewfile with the latest installed packages.

### Changes
- Updated Brewfile via \`brew bundle dump\`
- Timestamp: $(date '+%Y-%m-%d %H:%M:%S')

### Validation
\`\`\`
brew bundle check --file=brew/Brewfile
\`\`\`

### Files Changed
$(git diff --name-only origin/main..HEAD | sed 's/^/- /')

---
*Generated by \`update-and-pr.sh\`*"

# Create PR
PR_URL=$(gh pr create \
    --repo "$REPO_PATH" \
    --base main \
    --head "$BRANCH_NAME" \
    --title "$COMMIT_MESSAGE" \
    --body "$PR_BODY")

log_success "Pull request created!"
echo
log_info "PR URL: $PR_URL"
echo

# Step 9: Open PR in browser (optional)
read -p "Open PR in browser? (Y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    gh pr view "$PR_URL" --web
fi

# Step 10: Return to original branch
log_info "Returning to $CURRENT_BRANCH branch..."
git checkout "$CURRENT_BRANCH"

# Summary
echo
log_success "All done!"
echo
echo "Summary:"
echo "  Branch: $BRANCH_NAME"
echo "  PR: $PR_URL"
echo "  Status: Ready for review"
echo
log_info "To merge: gh pr merge $PR_URL"
log_info "To delete branch: git branch -D $BRANCH_NAME && git push origin --delete $BRANCH_NAME"

exit 0
